### ISSUE TITLE
Make it configurable whether a failed batch job fails a task

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-task#201]
Currently if a batch job fails the task will still be marked 0 (success) because technically the task did complete and the batch job handled the exception.  However, we want to make this configurable such that if the user wants the task to be marked as a failure if the batch job fails.

**Comment by Chnoch** [comment]
Any progress on this issue? This would be especially helpful in combination with the newly available composed-task-runner on Spring Cloud Data Flow, since the composed task runner checks the exit status of the task execution. So even though our batch job fails the composed task runner thinks that it completed successfully and continues the execution of subsequent tasks.

**Comment by cppwfs** [comment]
This feature will be added as a part of the Task 2.0 release which is scheduled to follow Boot 2.0 release.

**Comment by sabbyanandan** [comment]
Depends on https://jira.spring.io/browse/BATCH-2640.

**Comment by sabbyanandan** [comment]
A new [JLCLR](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/batch/JobLauncherCommandLineRunner.java) would have to be implemented to have better control over the lifecycle.

**Comment by cppwfs** [comment]
After a discussion with @mminella   the following features need to added for this feature:
1) if a job fails an exception is thrown and no other jobs will be processed
2) if a job fails a error message will be logged stating the JobName, JobId, and JobExecution that failed.
