### ISSUE TITLE
How to handle failure when the database is down?

### ISSUE THREAD

**Issue by asarkar** [spring-cloud/spring-cloud-task#410]
What is the behavior of a task if the database goes down? At startup, and while in execution. Can I configure retry, and error handling behavior?

**Comment by asarkar** [comment]
@cppwfs
Retry is part of what I have in mind. The other part is ignoring the failure altogether. Based on the use case, user may deem the execution of the task more important than recording it, and decide that they can live without the taka being recorded as long as it ran to completion. Can we have an `ignoreTaskRecordingFailure` sort of thing?

I can take a shot at implementing 411 if it’s not picked up by someone else.

**Comment by cppwfs** [comment]
@asarkar 
You can always not specify a datasource and Task will use the MapTaskExecutionDAO.  So you get all the other features offered by task except the recording of the start and end of your task. 
 But I'm not sure we want to offer the ability to disable the recording of that data upon recording failure.   Because that would cause inconsistent task-execution history in certain cases.
But if you want to work on 411 that'd be awesome!

**Comment by mminella** [comment]
I'd argue that if the database is down, there are more serious issues that need to be addressed.  I don't know of many production environments where if a database is down, it's considered ok to continue doing things...

**Comment by asarkar** [comment]
@mminella Like I said, it’s dependent on the use case, and that is the task doing. For what I’m trying to use it, I can live without the result being recorded. No argument can be made general enough, because the choice is the user’s, not the framework developers’

**Comment by mminella** [comment]
What are the other features of Spring Cloud Task are you using that you want to keep working if the database log doesn't work?

**Comment by asarkar** [comment]
In my case, I am planning to (haven't written any code yet) use a `Task` to stream data from a HTTP endpoint into a database. If the task completes, but the task database is not available, I've still completed the streaming work and the effect is observable in the database. It takes about 30 min or so, and it doesn't make sense to fail the task given that the records have already been inserted in the DB, and I've no intention of rolling them back.

Hopefully this explains why I'm not putting too much emphasis on recording the task results.

**Comment by mminella** [comment]
Are you writing the results in the same database?  If so, if the task can't write to the db, I'd expect your process cannot either which means you'd want the task to fail.  If they are separate databases, I'm wondering if you need Spring Cloud Task at all.  If you don't care about the tracking of your app then why use it at all since you aren't using any of the other features in the framework.  Don't get me wrong, I'm not trying to discourage you from using Spring Cloud Task, but if you don't need the tracking what do you get from it?

**Comment by asarkar** [comment]
> Are you writing the results in the same database

Yes

> I'd expect your process cannot either

There is a window between the program writing and the task writing to the DB. The program would commit multiple times, and continue on failure, such that if a micro batch fails, the rest of the process doesn’t. I don’t want the 30 min or so dataloading to become a transaction-ish.

> but if you don't need the tracking what do you get from it?

It’s not that I don’t need the tracking, but it’s not critical to me. The tracking is nice, and combined with Spring Batch, I get restarts, retries and other goodies.

The point I’m trying to make here is that assuming the DB is always available is flies in the face of 12-factor app design. Since task is part of the Spring Cloud suite, I’d expect it to be Cloud friendly.
