### ISSUE TITLE
Upgrade Spring Cloud Build to 2.1.0 BS

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-task#439]
As a developer, I'd like to upgrade the framework to Spring Cloud v2.1 stack. 

**Acceptance:**
- Core framework is compatible with upstream v2.1 stack
- Identify and document deprecations
- Document migration notes if any
- Tests run successfully

**Comment by cppwfs** [comment]
While working on this PR we identified the problems 

* Stream/Task tests failed due to the override issue. SCSt fixed the issue.  [resolved]
* SCSt forced task to pull in Reactor dependencies when using SCSt [resolved]
* Had to research why we were getting override issue with JobCommandLineRunner override. [resolved]
* TaskBatchAutoConfiguration failed to initialize  [resolved]
* SCSt failed to send messages because Task would send messages prior to stream subscribing to channel [resolved]
* Research why @AfterTask/@BeforeTask failed to work without the @EnableTask annotation which is now deprecated.
