### ISSUE TITLE
Incorrect reference to `DefaultStepExecutionHandler` in docs

### ISSUE THREAD

**Issue by benas** [spring-cloud/spring-cloud-task#728]
The last sentence in the [Remote Partitioning](https://docs.spring.io/spring-cloud-task/docs/current/reference/#batch-partitioning) section of the reference documentation seems incorrect:

> The following example shows how to configure the DefaultStepExecutionHandler:

```java
@Bean
public DeployerStepExecutionHandler stepExecutionHandler(JobExplorer jobExplorer) {
	DeployerStepExecutionHandler handler =
		new DeployerStepExecutionHandler(this.context, jobExplorer, this.jobRepository);

	return handler;
}
```

The text mentions `DefaultStepExecutionHandler` but the example is about `DeployerStepExecutionHandler`.

**Comment by DavidGrath** [comment]
Over a month ago. I guess I'll fix this typo.
One thing I don't get, though.
This directory: https://github.com/spring-cloud/spring-cloud-task/tree/master/spring-cloud-task-docs
doesn't seem to have the docs in anywhere

**Comment by benas** [comment]
@DavidGrath docs are in the `asciidoc` directory: https://github.com/spring-cloud/spring-cloud-task/tree/master/spring-cloud-task-docs/src/main/asciidoc

The file containing the typo is the following: https://github.com/spring-cloud/spring-cloud-task/blob/master/spring-cloud-task-docs/src/main/asciidoc/batch.adoc

The fix consists in changing line 121 as follows:

```diff
- `Step`. The following example shows how to configure the `DefaultStepExecutionHandler`:
+ `Step`. The following example shows how to configure the `DeployerStepExecutionHandler `:
```

You are welcome to contribute if you want!

**Comment by DavidGrath** [comment]
Wonderful. Thank you!
Though an issue has come up with Github Actions, and now the pull request has a failed status.
https://github.com/spring-cloud/spring-cloud-task/actions/runs/370122984
It seems to be a 401 Unauthorized error with Maven on line 3753 of the build (ubuntu-latest) task logs:
> Error:  Failed to execute goal on project spring-cloud-task-core: Could not resolve dependencies for project org.springframework.cloud:spring-cloud-task-core:jar:2.3.0-SNAPSHOT: Failed to collect dependencies at javax:javaee-api:jar:8.0: Failed to read artifact descriptor for javax:javaee-api:jar:8.0: Could not transfer artifact javax:javaee-api:pom:8.0 from/to spring-plugins (https://repo.spring.io/plugins-release): Authentication failed for https://repo.spring.io/plugins-release/javax/javaee-api/8.0/javaee-api-8.0.pom 401 Unauthorized -> [Help 1]

Which is a bit confusing since there was no Java code written at all, and according to:
https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/re-running-a-workflow
> Write access to the repository is required to perform these steps.

I'm not requesting write access, but I'd like to know whether I needed any extra privileges before performing the pull request.

**Comment by cppwfs** [comment]
Already fixed.
